### ISSUE TITLE
Map shows as pending despite being ranked

### ISSUE THREAD

**Issue by abraker95** [Sebola3461/osumodhub#1]
See: https://osumodhub.herokuapp.com/queue/4635891

**Comment by Sebola3461** [comment]
Your queue doesnt have any request...

**Comment by Hiviexd** [comment]
I think "Pending" is just the status of the request in the queue, not the map's ranked status

**Comment by Sebola3461** [comment]
> I think "Pending" is just the status of the request in the queue, not the map's ranked status

Yes, you can't request ranked beatmaps

**Comment by abraker95** [comment]
Oh I see. Maybe somehow make it clearer that it's status of request and not map's status?
