### ISSUE TITLE
Add dynamic loading to main page and modder's page.

### ISSUE THREAD

**Issue by Kapitar** [Sebola3461/osumodhub#6]
![image](https://user-images.githubusercontent.com/52191611/187383374-440dbb42-51a7-4de7-b5eb-134d49d2b148.png)
Perfomance of current loading is kinda annoying 4 seconds for loading requests. Consider making dynamic loading like in osu beatmaps sections https://osu.ppy.sh/beatmapsets

**Comment by Sebola3461** [comment]
alrd. i will start this today

**Comment by Sebola3461** [comment]
![image](https://user-images.githubusercontent.com/62405013/187554050-482bb53f-ac66-447d-afc8-62a6345b8bb9.png)
I processed all requests again to save the beatmap data in the request, so, it's quick now

**Comment by Sebola3461** [comment]
it's working now
